name = "Wrangling"
uuid = "9e19721c-8a1a-4e7b-ae00-562464868f98"
authors = ["Invenia Technical Computing Corporation"]
version = "0.1.2"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
Compat = "3.15"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
